/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlCategoria;
import control.ControlLike;
import control.ControlPost;
import control.ControlUsuario;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.categoria;
import modelo.like;
import modelo.post;
import modelo.usuario;
import static vista.Login.correoglobal;

/**
 *
 * @author USER
 */
public class VistaBuscar extends javax.swing.JFrame {

    /**
     * Creates new form VistaBuscar
     */
    LinkedList<like> listalikes;
    LinkedList<post> listaposts;
    LinkedList<categoria> listacategoria;
    LinkedList<usuario> listausuarios;
    LinkedList<like> listausuarioDarLike;
    int i = 0;
    int j = 0;
    int k = 0;
    int contadorlike = 0;
    boolean llegada = false;
    String categoriasL="";
    String buscador="";
    String buscador2="";
    
    //las categorias
    int flores=1;
    int ropa=2;
    
    public VistaBuscar() {
        initComponents();
        
        listaposts = new LinkedList<>();
        listacategoria = new LinkedList<>();
        listalikes = new LinkedList<>();
        listausuarios = new LinkedList<>();
        consultalikeBoton();
        
        ComboCategorias.setVisible(false);
       jPanel1.setVisible(false);
        
      
        etiquetas.setVisible(false);
       btnEtiqueta.setVisible(false);
       btnFecha.setVisible(false);
        btnRangoFecha.setVisible(false);
        fecha.setVisible(false);
        fecha2.setVisible(false);
         fechal.setVisible(false);
        al.setVisible(false);
        fecha1.setVisible(false);
        verpostInicial();
        verLike();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelimage1 = new javax.swing.JLabel();
        labelLikes1 = new javax.swing.JLabel();
        labelLike1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescripcion1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        labeletiqueta1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btncategoria1 = new javax.swing.JButton();
        btnlike1 = new javax.swing.JButton();
        btnfav1 = new javax.swing.JButton();
        btnvercomentarios1 = new javax.swing.JButton();
        btnant1 = new javax.swing.JButton();
        btnsiguiente1 = new javax.swing.JButton();
        labelcorreo = new javax.swing.JLabel();
        CheckCategorias = new javax.swing.JCheckBox();
        ComboCategorias = new javax.swing.JComboBox<>();
        CheckEtiquetas = new javax.swing.JCheckBox();
        etiquetas = new javax.swing.JTextField();
        CheckFecha = new javax.swing.JCheckBox();
        fechal = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        CheckRangoFecha = new javax.swing.JCheckBox();
        fecha1 = new javax.swing.JTextField();
        al = new javax.swing.JLabel();
        fecha2 = new javax.swing.JTextField();
        btnEtiqueta = new javax.swing.JButton();
        btnFecha = new javax.swing.JButton();
        btnRangoFecha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("BUSCADOR");

        labelLikes1.setText("likes");

        labelLike1.setText("jLabel3");

        txtdescripcion1.setEditable(false);
        txtdescripcion1.setColumns(20);
        txtdescripcion1.setRows(5);
        jScrollPane2.setViewportView(txtdescripcion1);

        jLabel9.setText("Etiqueta:");

        labeletiqueta1.setText("jLabel2");

        jLabel8.setText("Categoria:");

        btncategoria1.setText("jButton1");

        btnlike1.setText("Me gusta");
        btnlike1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlike1ActionPerformed(evt);
            }
        });

        btnfav1.setText("Favoritos");

        btnvercomentarios1.setText("Ver comentarios");

        btnant1.setText("Anterior");
        btnant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnant1ActionPerformed(evt);
            }
        });

        btnsiguiente1.setText("Siguiente");
        btnsiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguiente1ActionPerformed(evt);
            }
        });

        labelcorreo.setForeground(new java.awt.Color(102, 102, 255));
        labelcorreo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labeletiqueta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvercomentarios1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnant1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                        .addComponent(btnsiguiente1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelcorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelLikes1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLike1)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnlike1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnfav1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelimage1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLikes1)
                    .addComponent(labelLike1)
                    .addComponent(labelcorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(labeletiqueta1))
                    .addComponent(btnvercomentarios1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btncategoria1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlike1)
                    .addComponent(btnfav1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnant1)
                    .addComponent(btnsiguiente1)))
        );

        CheckCategorias.setText("Buscar por categorias");
        CheckCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCategoriasActionPerformed(evt);
            }
        });

        ComboCategorias.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ComboCategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboCategoriasItemStateChanged(evt);
            }
        });
        ComboCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCategoriasActionPerformed(evt);
            }
        });

        CheckEtiquetas.setText("Buscar por etiquetas");
        CheckEtiquetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEtiquetasActionPerformed(evt);
            }
        });

        CheckFecha.setText("Buscar por fechas");
        CheckFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckFechaActionPerformed(evt);
            }
        });

        fechal.setText("Digite una fecha");

        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        CheckRangoFecha.setText("Buscar por rango de fechas");
        CheckRangoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckRangoFechaActionPerformed(evt);
            }
        });

        fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha1ActionPerformed(evt);
            }
        });

        al.setText("á");

        btnEtiqueta.setText("Buscar");
        btnEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtiquetaActionPerformed(evt);
            }
        });

        btnFecha.setText("Buscar");
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });

        btnRangoFecha.setText("Buscar");
        btnRangoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRangoFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(329, 329, 329))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEtiqueta)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CheckCategorias)
                                    .addGap(18, 18, 18)
                                    .addComponent(CheckEtiquetas))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ComboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(etiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechal)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnFecha)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckFecha)
                                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(al, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CheckRangoFecha)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnRangoFecha)
                                        .addGap(43, 43, 43)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckCategorias)
                    .addComponent(CheckEtiquetas)
                    .addComponent(CheckFecha)
                    .addComponent(CheckRangoFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(al)
                    .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEtiqueta)
                    .addComponent(btnFecha)
                    .addComponent(btnRangoFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlike1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlike1ActionPerformed
        // TODO add your handling code here:
        ControlLike cl = new ControlLike();

        if (llegada == false) {

            like nuevolike = new like(listaposts.get(i).getIdpost(), correoglobal);
            cl.insertarLike(nuevolike);

            // btnlike.setText("Me gusta");
        } else if (llegada == true) {

            like nuevolike = new like(listaposts.get(i).getIdpost(), correoglobal);
            cl.BorrarLikes(nuevolike);

        }
        consultalikeBoton();
        verLike();
    }//GEN-LAST:event_btnlike1ActionPerformed

    private void btnant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnant1ActionPerformed
        // TODO add your handling code here:

        if ((i <= listaposts.size()) && i >= 0) {
            if (i == 0) {
                JOptionPane.showMessageDialog(rootPane, "No hay más contenido");
            } else {
                i--;
                if(CheckCategorias.isSelected()== true){
                 verpost();
                verLike();
                consultalikeBoton();
                }
            }

        }
       
        //System.out.println(i);
    }//GEN-LAST:event_btnant1ActionPerformed


    private void btnsiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguiente1ActionPerformed
        // TODO add your handling code here:

        if ((i <= listaposts.size()) && i >= 0) {
            if (i == (listaposts.size() - 1)) {
                JOptionPane.showMessageDialog(rootPane, "Actualice su feed");
            } else {
                i++;
                if(CheckCategorias.isSelected()== true){
                 verpost();
                verLike();
                consultalikeBoton();
                }if(CheckEtiquetas.isSelected()== true){
                verpost2();
                verLike();
                consultalikeBoton();
                }
                if(CheckFecha.isSelected()== true){
                verpost3();
                verLike();
                consultalikeBoton();
                }
                if(CheckRangoFecha.isSelected()== true){
                verpost4();
                verLike();
                consultalikeBoton();
                }
            }

        }
        // System.out.println(i);
        
    }//GEN-LAST:event_btnsiguiente1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ControlCategoria objcc = new ControlCategoria();
        listacategoria = objcc.consultarCategoria();
        for (int j = 0; j < listacategoria.size(); j++) {
            categoria objcategoria = listacategoria.get(j);
            ComboCategorias.addItem(objcategoria.getTipoCategoria());
        } 
    }//GEN-LAST:event_formWindowOpened

    private void CheckCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCategoriasActionPerformed
        // TODO add your handling code here:
         if(CheckCategorias.isSelected()== true){
            ComboCategorias.setVisible(true);
            jPanel1.setVisible(true); 
            CheckRangoFecha.setVisible(false);
            CheckFecha.setVisible(false);
            CheckEtiquetas.setVisible(false);
            
    }else{
         ComboCategorias.setVisible(false);
         CheckRangoFecha.setVisible(true);
            CheckFecha.setVisible(true);
            CheckEtiquetas.setVisible(true);
         
         }    
    }//GEN-LAST:event_CheckCategoriasActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void CheckEtiquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEtiquetasActionPerformed
       if(CheckEtiquetas.isSelected()){
            etiquetas.setVisible(true);
            jPanel1.setVisible(true);
             CheckRangoFecha.setVisible(false);
            CheckFecha.setVisible(false);
            CheckCategorias.setVisible(false);
            btnEtiqueta.setVisible(true);
      
    }else{
         etiquetas.setVisible(false);
          CheckRangoFecha.setVisible(true);
            CheckFecha.setVisible(true);
            CheckCategorias.setVisible(true);
            btnEtiqueta.setVisible(false);
         
         } 
        
        
    }//GEN-LAST:event_CheckEtiquetasActionPerformed

    private void CheckFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckFechaActionPerformed
       if(CheckFecha.isSelected()){
            fecha.setVisible(true);
             fechal.setVisible(true);
             jPanel1.setVisible(true);
             CheckRangoFecha.setVisible(false);
            CheckEtiquetas.setVisible(false);
            CheckCategorias.setVisible(false);
            btnFecha.setVisible(true);
      
    }else{
         fecha.setVisible(false);
             fechal.setVisible(false);
             CheckRangoFecha.setVisible(true);
            CheckEtiquetas.setVisible(true);
            CheckCategorias.setVisible(true);
            btnFecha.setVisible(false);
         
         } 
        
    }//GEN-LAST:event_CheckFechaActionPerformed

    private void CheckRangoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckRangoFechaActionPerformed
       if(CheckRangoFecha.isSelected()){
            fecha1.setVisible(true);
            fecha2.setVisible(true);
            al.setVisible(true);
            jPanel1.setVisible(true);
            CheckCategorias.setVisible(false);
            CheckFecha.setVisible(false);
            CheckEtiquetas.setVisible(false);
            btnRangoFecha.setVisible(true);
    }else{
         fecha1.setVisible(false);
            fecha2.setVisible(false);
            al.setVisible(false);
            CheckCategorias.setVisible(true);
            CheckFecha.setVisible(true);
            CheckEtiquetas.setVisible(true);
            btnRangoFecha.setVisible(false);
           
         
         } 
    }//GEN-LAST:event_CheckRangoFechaActionPerformed

    private void fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha1ActionPerformed

    private void btnEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtiquetaActionPerformed
        // TODO add your handling code here:
        i=0;
        verpost2();
        
        
        
    }//GEN-LAST:event_btnEtiquetaActionPerformed

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
        // TODO add your handling code here:
        i=0;
        verpost3();
        
        
    }//GEN-LAST:event_btnFechaActionPerformed

    private void btnRangoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRangoFechaActionPerformed
        // TODO add your handling code here:
        i=0;
        verpost4();
        
    }//GEN-LAST:event_btnRangoFechaActionPerformed
      
    private void ComboCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCategoriasActionPerformed

    private void ComboCategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboCategoriasItemStateChanged
        i = 0;
       verpost();
       
    }//GEN-LAST:event_ComboCategoriasItemStateChanged
      private void consultalikeBoton() {
        ControlUsuario cu = new ControlUsuario();
        listausuarios = cu.consultarUsuarios(correoglobal);//esta lista va a consultar solo la id de mi login
        ControlLike cl = new ControlLike();
        listausuarioDarLike = cl.consultarLikes();
        for (int u = 0; u < listausuarios.size(); u++) {

            llegada = cl.consultarLikesPorUsuario(listaposts.get(i).getIdpost(), listausuarios.get(u).getCorreoU());

            if (llegada == true) {
                btnlike1.setText("No Me gusta");

                System.out.println(llegada);
                break;
            } else {
                btnlike1.setText("Me gusta");

                System.err.println(llegada);
                break;
            }

        }

    }
      private void verpostInicial() {
        try {
            
            ControlPost cp = new ControlPost();
            
            listaposts = cp.consultarPosts();
            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage1.getWidth(), labelimage1.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage1.setIcon(newIcon);
            labeletiqueta1.setText(listaposts.get(i).getEtiqueta());

            txtdescripcion1.setText(listaposts.get(i).getDescripcion());

            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i).getIdCategoriastf()) {
                    int categorias = listaposts.get(i).getIdCategoriastf();
                    btncategoria1.setText(listacategoria.get(j).getTipoCategoria());

                }

            }
            labelcorreo.setText(listaposts.get(i).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     
    private void verpost() {// si el usuario ha seleccionado alguna categoria
        try {

            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
            categoriasL = String.valueOf(ComboCategorias.getSelectedItem());
            ControlPost cp = new ControlPost();
            listaposts = cp.BusquedaPosts2(categoriasL);

            
            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i).getIdCategoriastf()) {
                    int categorias = listaposts.get(i).getIdCategoriastf(); 
                    btncategoria1.setText(listacategoria.get(j).getTipoCategoria());
                    BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage1.getWidth(), labelimage1.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage1.setIcon(newIcon);
            labeletiqueta1.setText(listaposts.get(i).getEtiqueta());

            txtdescripcion1.setText(listaposts.get(i).getDescripcion());
            labelcorreo.setText(listaposts.get(i).getCorreoUF());

                }

            }
            
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
           
        }
    }
    private void verpost2() {// este metodo se utiliza,si el usuario ha seleccionado buscar por etiquetas
        try {
              
            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
            buscador= etiquetas.getText();  
             System.err.println("etiqueta: " + buscador);            
            ControlPost cp = new ControlPost();
            listaposts = cp.BusquedaPostsPorEtiqueta(buscador.toLowerCase());
            
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i).getFotoPelicula()));
          
            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage1.getWidth(), labelimage1.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage1.setIcon(newIcon);
            labeletiqueta1.setText(listaposts.get(i).getEtiqueta());

            txtdescripcion1.setText(listaposts.get(i).getDescripcion());
            
            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i).getIdCategoriastf()) {
                    
            int categorias = listaposts.get(i).getIdCategoriastf();
            btncategoria1.setText(listacategoria.get(j).getTipoCategoria());
           
            
            

                }

            }
            labelcorreo.setText(listaposts.get(i).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no se encontraron resultados");
            
        }
    }
    
     private void verpost3() {// si el usuario ha seleccionado fecha
        try {

            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
            buscador= fecha.getText();
            ControlPost cp = new ControlPost();
            listaposts = cp.BusquedaPostPorFecha(buscador);
            

            
            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i).getIdCategoriastf()) {
                    int categorias = listaposts.get(i).getIdCategoriastf();
                    btncategoria1.setText(listacategoria.get(j).getTipoCategoria());
      
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage1.getWidth(), labelimage1.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage1.setIcon(newIcon);
            labeletiqueta1.setText(listaposts.get(i).getEtiqueta());

            txtdescripcion1.setText(listaposts.get(i).getDescripcion());

                }

            }
            labelcorreo.setText(listaposts.get(i).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no se encontraron resultados");
        }
    }
     private void verpost4() {// si el usuario ha seleccionado rango de fecha
        try {

            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
            buscador= fecha1.getText();
             buscador2 =fecha2.getText();
             System.err.println("etiqueta: " + buscador);
             System.err.println("etiqueta: " + buscador2);
             
            ControlPost cp = new ControlPost();
            listaposts = cp.BusquedaPostPorRangoFecha(buscador,buscador2);
            

            
            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i).getIdCategoriastf()) {
                    int categorias = listaposts.get(i).getIdCategoriastf();
                    btncategoria1.setText(listacategoria.get(j).getTipoCategoria());
      
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage1.getWidth(), labelimage1.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage1.setIcon(newIcon);
            labeletiqueta1.setText(listaposts.get(i).getEtiqueta());

            txtdescripcion1.setText(listaposts.get(i).getDescripcion());

                }

            }
            labelcorreo.setText(listaposts.get(i).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
           System.out.println("no se encontraron resultados");
        }
    }
   
    private void verLike() {

        ControlLike objcl = new ControlLike();
        listalikes = objcl.consultarLikes();

        int cantlikes = objcl.consultarCantidadLikes(listaposts.get(i).getIdpost());
        labelLike1.setText(String.valueOf(cantlikes));

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckCategorias;
    private javax.swing.JCheckBox CheckEtiquetas;
    private javax.swing.JCheckBox CheckFecha;
    private javax.swing.JCheckBox CheckRangoFecha;
    private javax.swing.JComboBox<String> ComboCategorias;
    private javax.swing.JLabel al;
    private javax.swing.JButton btnEtiqueta;
    private javax.swing.JButton btnFecha;
    private javax.swing.JButton btnRangoFecha;
    private javax.swing.JButton btnant1;
    private javax.swing.JButton btncategoria1;
    private javax.swing.JButton btnfav1;
    private javax.swing.JButton btnlike1;
    private javax.swing.JButton btnsiguiente1;
    private javax.swing.JButton btnvercomentarios1;
    private javax.swing.JTextField etiquetas;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fecha1;
    private javax.swing.JTextField fecha2;
    private javax.swing.JLabel fechal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelLike1;
    private javax.swing.JLabel labelLikes1;
    private javax.swing.JLabel labelcorreo;
    private javax.swing.JLabel labeletiqueta1;
    private javax.swing.JLabel labelimage1;
    private javax.swing.JTextArea txtdescripcion1;
    // End of variables declaration//GEN-END:variables
}
