/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlCategoria;
import control.ControlComentario;
import control.ControlLike;
import control.ControlPost;
import control.ControlUsuario;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.categoria;
import modelo.comentario;
import modelo.like;
import modelo.post;
import modelo.usuario;
import static vista.Login.correoglobal;

/**
 *
 * @author natal
 */
public class VistaCategoria extends javax.swing.JFrame {

    /**
     * Creates new form VistaCategorias
     */
    LinkedList<like> listalikes;
    LinkedList<post> listaposts;
    LinkedList<categoria> listacategoria;
    LinkedList<usuario> listausuarios;
    LinkedList<like> listausuarioDarLike;//esta lista será para evaluar al usuario que dió like
    int i = 0;
    int j = 0;
    int k = 0;
    int contadorlike = 0;
    boolean llegada = false;
    String categoriacmb = " ";
    

    public VistaCategoria() {
        initComponents();
        listacategoria = new LinkedList<>();
        listaposts = new LinkedList<>();
        listalikes = new LinkedList<>();
        AreaComentario.setVisible(false);
        verpost();
        verLike();
        consultalikeBoton();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbcategorias = new javax.swing.JComboBox<>();
        labelcorreo = new javax.swing.JLabel();
        labelLikes = new javax.swing.JLabel();
        labelLike = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        labeletiqueta = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnlike = new javax.swing.JButton();
        btnfav = new javax.swing.JButton();
        btnvercomentarios = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btnsiguiente = new javax.swing.JButton();
        btnant = new javax.swing.JButton();
        labelimage = new javax.swing.JLabel();
        btncategoria = new javax.swing.JButton();
        BtnComentar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaComentario = new javax.swing.JTextArea();
        aggComentario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Categorias");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Elegir Categoria");

        cmbcategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbcategoriasItemStateChanged(evt);
            }
        });
        cmbcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcategoriasActionPerformed(evt);
            }
        });

        labelcorreo.setForeground(new java.awt.Color(102, 102, 255));
        labelcorreo.setText("jLabel1");

        labelLikes.setText("likes");

        labelLike.setText("jLabel3");

        txtdescripcion.setEditable(false);
        txtdescripcion.setColumns(20);
        txtdescripcion.setRows(5);
        jScrollPane1.setViewportView(txtdescripcion);

        labeletiqueta.setText("jLabel2");

        jLabel3.setText("Etiqueta:");

        jLabel4.setText("Categoria:");

        btnlike.setText("Me gusta");
        btnlike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlikeActionPerformed(evt);
            }
        });

        btnfav.setText("Favoritos");

        btnvercomentarios.setText("Ver comentarios");

        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });

        btnant.setText("Anterior");
        btnant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnantActionPerformed(evt);
            }
        });

        btncategoria.setText("jButton1");
        btncategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoriaActionPerformed(evt);
            }
        });

        BtnComentar.setText("Comentar");
        BtnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComentarActionPerformed(evt);
            }
        });

        AreaComentario.setColumns(20);
        AreaComentario.setRows(5);
        jScrollPane2.setViewportView(AreaComentario);

        aggComentario.setText("Hacer Comentario");
        aggComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggComentarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsiguiente)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(labeletiqueta))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelcorreo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelLikes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelLike))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(aggComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncategoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlike)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnfav)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnvercomentarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnComentar)))
                        .addGap(46, 46, 46))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(labelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(411, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbcategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelimage, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelcorreo)
                    .addComponent(labelLikes)
                    .addComponent(labelLike))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labeletiqueta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btncategoria)
                    .addComponent(btnlike)
                    .addComponent(btnfav)
                    .addComponent(btnvercomentarios)
                    .addComponent(BtnComentar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aggComentario)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsiguiente)
                    .addComponent(btnant))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(619, 619, 619)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoriasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbcategoriasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      ControlCategoria objcc = new ControlCategoria();
        listacategoria = objcc.consultarCategoria();
        for (int j = 0; j < listacategoria.size(); j++) {
            categoria objcategoria = listacategoria.get(j);
            cmbcategorias.addItem(objcategoria.getTipoCategoria());
        }


    }//GEN-LAST:event_formWindowOpened

    private void btnlikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlikeActionPerformed
        // TODO add your handling code here:
        ControlLike cl = new ControlLike();

        if (llegada == false) {

            like nuevolike = new like(listaposts.get(i).getIdpost(), "123");
            cl.insertarLike(nuevolike);

            // btnlike.setText("Me gusta");
        } else if (llegada == true) {

            like nuevolike = new like(listaposts.get(i).getIdpost(), "123");
            cl.BorrarLikes(nuevolike);

        }
        consultalikeBoton();
        verLike();

    }//GEN-LAST:event_btnlikeActionPerformed

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        // TODO add your handling code here:

        System.err.println("CATEGORIA: " + categoriacmb);
        if ((i <= listaposts.size()) && i >= 0) {
            if (i == (listaposts.size() - 1)) {
                JOptionPane.showMessageDialog(rootPane, "Actualice su feed");
            } else {
                i++;
                verpost2();
                verLike();
                consultalikeBoton();

            }

        }
      System.out.println(i);
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btnantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnantActionPerformed
        // TODO add your handling code here:

        if ((i <= listaposts.size()) && i >= 0) {
            if (i == 0) {
                JOptionPane.showMessageDialog(rootPane, "No hay más contenido");
            } else {
                i--;
                verpost2();
                verLike();
                consultalikeBoton();
            }

        }
      System.out.println(i);
    }//GEN-LAST:event_btnantActionPerformed

    private void cmbcategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbcategoriasItemStateChanged
        // TODO add your handling code here:
        i = 0;
       verpost2();
    }//GEN-LAST:event_cmbcategoriasItemStateChanged

    private void btncategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncategoriaActionPerformed

    private void BtnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComentarActionPerformed
       
       AreaComentario.setVisible(true); 
        
    }//GEN-LAST:event_BtnComentarActionPerformed

    private void aggComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggComentarioActionPerformed
        
        HacerComentario();
    }//GEN-LAST:event_aggComentarioActionPerformed

    public void consultalikeBoton() {
        System.err.println("Entré al metodo");
        ControlUsuario cu = new ControlUsuario();
        listausuarios = cu.consultarUsuarios("123");//esta lista va a consultar solo la id de mi login
        ControlLike cl = new ControlLike();
        listausuarioDarLike = cl.consultarLikes();
        for (int u = 0; u < listausuarios.size(); u++) {

            llegada = cl.consultarLikesPorUsuario(listaposts.get(i).getIdpost(), listausuarios.get(u).getCorreoU());

            if (llegada == true) {
                btnlike.setText("No Me gusta");

                System.out.println(llegada);
                break;
            } else {
                btnlike.setText("Me gusta");

                System.err.println(llegada);
                break;
            }

        }

    }

    private void verpost() {
        try {
            ControlPost cp = new ControlPost();
            listaposts = cp.consultarPosts();
            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage.getWidth(), labelimage.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage.setIcon(newIcon);
            labeletiqueta.setText(listaposts.get(i).getEtiqueta());

            txtdescripcion.setText(listaposts.get(i).getDescripcion());

            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i).getIdCategoriastf()) {
                    int categorias = listaposts.get(i).getIdCategoriastf();
                    btncategoria.setText(listacategoria.get(j).getTipoCategoria());
                }

            }
            labelcorreo.setText(listaposts.get(i).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verpost2() {
        try {

            //categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            //Object[] fila = new Object[ncol];
            //// 
                          categoriacmb = String.valueOf(cmbcategorias.getSelectedItem());
            ControlPost cp = new ControlPost();
            listaposts = cp.BusquedaPosts2(categoriacmb);
            System.out.println("CATEGORIA INICIAL " + cmbcategorias.getSelectedItem());
            System.out.print(listacategoria);

            
            for (j = 0; j < listacategoria.size(); j++) {

                if (listacategoria.get(j).getIdCategoriast() == listaposts.get(i).getIdCategoriastf()) {
                    int categorias = listaposts.get(i).getIdCategoriastf();
                    btncategoria.setText(listacategoria.get(j).getTipoCategoria());
      
            BufferedImage img = ImageIO.read(new ByteArrayInputStream(listaposts.get(i).getFotoPelicula()));

            ImageIcon imageIcon = new ImageIcon(img);
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(labelimage.getWidth(), labelimage.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ImageIcon newIcon = new ImageIcon(newImage);
            labelimage.setIcon(newIcon);
            labeletiqueta.setText(listaposts.get(i).getEtiqueta());

            txtdescripcion.setText(listaposts.get(i).getDescripcion());

                }

            }
            labelcorreo.setText(listaposts.get(i).getCorreoUF());
            ///     
            //txtcategoria.setText(Integer.toString(categorias));

        } catch (IOException ex) {
            Logger.getLogger(VistaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void verLike() {

        ControlLike objcl = new ControlLike();
        listalikes = objcl.consultarLikes();

        int cantlikes = objcl.consultarCantidadLikes(listaposts.get(i).getIdpost());
        labelLike.setText(String.valueOf(cantlikes));

    }
    private void HacerComentario(){
    
    String Comentario = AreaComentario.getText();
    int IDpost=listaposts.get(i).getIdpost();
    String CorreoUsuario= "correoluisa@hotmail.com"; // aqui iria el correoGlobal xd
     comentario nuevoComentario= new comentario(Comentario, IDpost, CorreoUsuario);
     ControlComentario objC= new ControlComentario();
      boolean t= objC.insertarComentario(nuevoComentario);
    if(t==true){
            JOptionPane.showMessageDialog(rootPane, "Se insertó el comentario");
            
        }else {
               JOptionPane.showMessageDialog(rootPane, "No se insertó el comentario");
        }
    
    
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaComentario;
    private javax.swing.JButton BtnComentar;
    private javax.swing.JButton aggComentario;
    private javax.swing.JButton btnant;
    private javax.swing.JButton btncategoria;
    private javax.swing.JButton btnfav;
    private javax.swing.JButton btnlike;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton btnvercomentarios;
    private javax.swing.JComboBox<String> cmbcategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelLike;
    private javax.swing.JLabel labelLikes;
    private javax.swing.JLabel labelcorreo;
    private javax.swing.JLabel labeletiqueta;
    private javax.swing.JLabel labelimage;
    private javax.swing.JTextArea txtdescripcion;
    // End of variables declaration//GEN-END:variables
}
